### ISSUE TITLE
Typos in solutions

### ISSUE THREAD

**Issue by Peixuan670** [sdrangan/introml#16]
Hello Professor Rangan,
This is Peixuan. I found 2 typos in HW7:
1. Section 2, Problem 3, J should be f(z)
2, Section 3, Problem 2(b): solution dL/duij shouldn't sum over i

**Comment by sdrangan** [comment]
Fixed.  
https://github.com/sdrangan/introml/commit/58c2d1d0215b5c7fdde40038549f2282bd5e08b7
